### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by toto-ldd** [jiewenhuang/halo-theme-stack#14]
![image](https://user-images.githubusercontent.com/43908332/228814624-be0d9c44-57a2-470e-b29d-ed9d9e3e951d.png)
应该显示出所有标签

**Comment by jiewenhuang** [comment]
> ![image](https://user-images.githubusercontent.com/43908332/228814624-be0d9c44-57a2-470e-b29d-ed9d9e3e951d.png) 应该显示出所有标签

这个应该是分类，为了美观只取了第一个分类。标签在内容页底部是全部列出的。
