### ISSUE TITLE
如何实现像您主页中的效果

### ISSUE THREAD

**Issue by zhouyan553** [jiewenhuang/halo-theme-stack#17]
您的主页友链栏中点击展开以及底下一块一块的友链是如何实现的
<img width="689" alt="image" src="https://user-images.githubusercontent.com/126075076/230551827-0db55fe6-5383-4968-8393-7fa04950d741.png">

**Comment by jiewenhuang** [comment]
使用链接管理插件即可：https://github.com/halo-sigs/plugin-links
