### ISSUE TITLE
waline评论插件无法使用

### ISSUE THREAD

**Issue by zhouyan553** [jiewenhuang/halo-theme-stack#18]
<img width="654" alt="image" src="https://user-images.githubusercontent.com/126075076/230723903-596ee930-8083-4f00-87ec-df9fa1be0069.png">
使用的docker安装waline，waline版本1.8.2

**Comment by jiewenhuang** [comment]
检查一下，waline是否正常，和服务器联通问题，这个应该跟主题这边没什么关系

**Comment by zhouyan553** [comment]
想问下大佬你是部署在哪里的呢

**Comment by jiewenhuang** [comment]
> 想问下大佬你是部署在哪里的呢

vercel
