### ISSUE TITLE
图片不显示

### ISSUE THREAD

**Issue by zhaoshuailongLxw** [jiewenhuang/halo-theme-stack#22]
后台设置分类 选择默认模板 ，前端点击查看分类图片没有（这里还是要设置分类必须要手动设计图片，使用默认模板也是没有图片）

**Comment by jiewenhuang** [comment]
<img width="876" alt="image" src="https://github.com/jiewenhuang/halo-theme-stack/assets/68629578/c68d2e70-0f26-43f5-a760-bb50b6ddd9e7">
这里设置分类封面，这个地方没写随机图
