### ISSUE TITLE
代码块里的代码文字太大了，能弄小点嘛，或者能加一个配置调节文字大小

### ISSUE THREAD

**Issue by wsdszhou** [jiewenhuang/halo-theme-stack#25]
代码块里的代码文字太大了，能弄小点嘛，或者能加一个配置调节文字大小

**Comment by jiewenhuang** [comment]
这个应该是不大的，可以配合[awesome-halo](https://github.com/halo-sigs/awesome-halo)中的代码高亮插件使用，如果还是觉得大可以自行给.article-content pre code增加font-size属性
