### ISSUE TITLE
菜单内主体不显示图片

### ISSUE THREAD

**Issue by txbxxx** [jiewenhuang/halo-theme-stack#30]
![image](https://github.com/jiewenhuang/halo-theme-stack/assets/79389617/d2b3e282-19c4-4f1d-aaaa-4efb19df0ec6)
请问这个图片在哪里设置呢，我设置icon图片还是没有
![image](https://github.com/jiewenhuang/halo-theme-stack/assets/79389617/1fc7fb5f-0226-4c3d-b8cc-dbff390b93af)

**Comment by emyia2001** [comment]
请问怎么解决的？
