### ISSUE TITLE
请问下，文章的随机图片都是显示一样的，这个要怎么设置下？

### ISSUE THREAD

**Issue by Jack-Ywn** [jiewenhuang/halo-theme-stack#5]
![image](https://user-images.githubusercontent.com/72083949/211158402-3e0efcbe-89f3-48d9-be50-697622ad46d4.png)

**Comment by jiewenhuang** [comment]
已修复，下载最新[压缩包](https://github.com/jiewenhuang/halo-theme-stack/releases/tag/v1.0.4)更新即可
