### ISSUE TITLE
添加友链在左侧菜单，然后点击友链之后提示500 内部服务器错误。

### ISSUE THREAD

**Issue by wixxm** [jiewenhuang/halo-theme-stack#54]
### 是什么版本出现了此问题？

添加友链在左侧菜单，然后点击友链之后提示500 内部服务器错误

### 发生了什么？

主题中菜单添加了/links添加友链在左侧菜单，然后点击友链之后提示500 内部服务器错误。

### 附加信息

![{960BABF8-C9B8-49a6-8CBE-E591C3EBD252}](https://github.com/jiewenhuang/halo-theme-stack/assets/94870224/78a7c1d2-8119-45ea-a506-925a9795d940)

**Comment by jiewenhuang** [comment]
/links 这个路由的页面在Stack2是没有写的，你需要在页面新建一个，别名输入其他，例如friends，然后模版选择友链模板即可

**Comment by wixxm** [comment]
> /links 这个路由的页面在Stack2是没有写的，你需要在页面新建一个，别名输入其他，例如friends，然后模版选择友链模板即可

好的感谢大佬，还有一个问题就是，搜索菜单栏也出现报错问题。
![{8F499408-FA79-445b-90A3-C59D98D47211}](https://github.com/jiewenhuang/halo-theme-stack/assets/94870224/7455c8ec-8c38-40ec-93aa-21708431afac)

**Comment by wixxm** [comment]
感谢大佬，搜索也照搬解决。

**Comment by wixxm** [comment]
再次感谢大佬
