### ISSUE TITLE
有设置中有links但页面中没有

### ISSUE THREAD

**Issue by xiangshangya** [jiewenhuang/halo-theme-stack#64]
### 是什么版本出现了此问题？

2.2.3

### 发生了什么？

安装主题后，/links报错500服务器内部错误，但其他主题没有问题，好像是templates中没有links.html，我使用的2.2.3版本，但来github查看发现这上面也没有

**Comment by emyia2001** [comment]
安装插件PluginLinks，页面别名还有个，用links会有冲突，下面的自定义模板选择友链

**Comment by xiangshangya** [comment]
> 安装插件PluginLinks，页面别名还有个，用links会有冲突，下面的自定义模板选择友链

安装插件好了，后面的意思是页面别名还有个links，在模板中使用links会有冲突吗，后面的解决方法可以详细说说吗，有点没看懂，感谢

**Comment by xiangshangya** [comment]
> 安装插件PluginLinks，页面别名还有个，用links会有冲突，下面的自定义模板选择友链
已经新建页面，命名为friends，模板选择为友链，但仍报错500，选择模板为搜索就可以跳转为搜索页面
![image](https://github.com/user-attachments/assets/cc3c76a4-3304-48ba-9586-913bfd3fbf48)
![image](https://github.com/user-attachments/assets/6b4552ba-d5f4-4cde-b574-16c2f09956e9)
![image](https://github.com/user-attachments/assets/1cb9ca02-b24d-4847-8e10-43d99eba09bf)
设置为搜索时，
![image](https://github.com/user-attachments/assets/87ebeb87-4c01-4d99-9a2a-9ebc15a6452b)
![image](https://github.com/user-attachments/assets/785003c7-46c3-4ea6-a49e-538933a88703)

**Comment by xiangshangya** [comment]
已解决，解决方法：更新了halo版本

**Comment by xiangshangya** [comment]
总结操作：新建页面，别名设置为除/links以外的，如/friends，模板选择友链，其余正常发布流程，在自己的地址+/friends查看，如果能直接打开则没问题，打不开尝试更新halo版本
