### ISSUE TITLE
主菜单界面的菜单项图标如何设置

### ISSUE THREAD

**Issue by emyia2001** [jiewenhuang/halo-theme-stack#65]

**Comment by jiewenhuang** [comment]
see https://www.jiewen.run/docs/stack/use/menuSetting

**Comment by emyia2001** [comment]
主题设置中没有自定义这个选项

**Comment by emyia2001** [comment]
主题设置中没有自定义这个选项![Screenshot_20240715_215517.jpg](https://github.com/user-attachments/assets/a1849fb0-a1e7-4048-a4d0-cea8bc1a292f)

**Comment by jiewenhuang** [comment]
只是让你参考，不是死脑的照抄。没有自定义引入，就自己去halo的设置那里引入进好了

**Comment by emyia2001** [comment]
好的，谢谢
