### ISSUE TITLE
v2.2.6友链跳转报500错误

### ISSUE THREAD

**Issue by ZPolister** [jiewenhuang/halo-theme-stack#66]
### 是什么版本出现了此问题？

2.2.6

### 在线站点地址

https://blog.polister.cn

### 发生了什么？

在启用Stack主题后，友链页面出现500内部错误，无法正常打开
路由配置为/links（应该没问题）

所使用的链接管理插件版本为1.4.0
可以点击上线网址中“小伙伴们”复现问题。

已经尝试过但无效的方法：
- 重新下载应用主题、链接插件
- 删除菜单重新添加

### 附加信息

![](https://sr-cdn.polister.cn/QQ_1721223135033.png)

错误信息截图

**Comment by jiewenhuang** [comment]
2.x版本没有适配默认的，下个小版本可能会做，现在，只能在页面那里新建页面选择友链模板的方式启用，记得不要跟links路由冲突

**Comment by ZPolister** [comment]
> 2.x版本没有适配默认的，下个小版本可能会做，现在，只能在页面那里新建页面选择友链模板的方式启用，记得不要跟links路由冲突

明白，感谢作者大大，辛苦！
