### ISSUE TITLE
阅读时长计算问题

### ISSUE THREAD

**Issue by WekyJay** [jiewenhuang/halo-theme-stack#8]
![image](https://user-images.githubusercontent.com/20734333/213713922-552831f3-8132-4de1-978f-fc16aa4d56ee.png)
一千多分钟可能有点吓人了....

**Comment by jiewenhuang** [comment]
网址有吗，内容先看看

**Comment by WekyJay** [comment]
我的个人网址：www.wekyjay.cn
&nbsp;


皮皮
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月20日(星期五) 晚上10:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jiewenhuang/halo-theme-stack] 阅读时长计算问题 (Issue #8)





 
网址有吗，内容先看看

**Comment by jiewenhuang** [comment]
排查发现是你图片的问题，使用了Data URI scheme会导致文章统计的字节过大，从而时间错误，换成正常图片即可

**Comment by WekyJay** [comment]
好的，感谢你的帮助！
