### ISSUE TITLE
require字段需要改为requires，2.0需改为2.0.0，否则Halo2.2报错

### ISSUE THREAD

**Issue by longjuan** [jiewenhuang/halo-theme-stack#9]
https://github.com/jiewenhuang/halo-theme-stack/blob/c5bff5a5eef5ea3dc9370be42171757394144c29/theme.yaml#L23
详见https://github.com/halo-dev/halo/pull/3150

**Comment by jiewenhuang** [comment]
https://github.com/jiewenhuang/halo-theme-stack/blob/9a0726f1d4ef8def3b892af7b8706252a7e8cb48/theme.yaml#L23
